### ISSUE TITLE
Get tests running using PyCall zarr dependency

### ISSUE THREAD

**Issue by meggart** [meggart/ZarrNative.jl#7]
The next step for me would be to create unit tests for reading and writing data to and from Directory stores. For this I would like to add Conda and PyCall as a test dependency to test against the latest version of zarr, i.e. we write a dataset with different chunkings, encodings, etc and test if the python zarr implementation can read it and if the values match and the other way around. 

We probably want PyCall and Conda only as a Test-specific dependency and this is going to be simple to specifiy from Julia 1.2 https://julialang.github.io/Pkg.jl/dev/creating-packages/#Test-specific-dependencies-1 , so @visr would you agree to set the lower bound of the package compatibility to Julia 1.2? I think it should be ok, since we are in very early stage anyway.

**Comment by visr** [comment]
Fine by me!

**Comment by meggart** [comment]
Fixed in #12
